name: Drake High School

description: Mountain Bike Team

avatar: https://raw.githubusercontent.com/krashanoff/drakeMTB/gh-pages/images/drakeMTBlogo.png

footer-links:
  dribbble:
  email:
  facebook: drakemtb
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter: drakehighschool
  stackoverflow:
  youtube: user/ironsprings
  googleplus: group/drakemtb 

disqus:

google_analytics: UA-67095911-2

url: http://krashanoff.github.io

baseurl: "/drakeMTB"

markdown: redcarpet
highlighter: pygments
permalink: /:title/

version: v1.1.0

sass:
  style: :compressed

gems:
  - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
